package dao;
import java.sql.Connection;
import java.sql.DriverManager;
public class ConnectionFactory {
    public Connection  getConexao() {
        try{
            return DriverManager.getConnection("jdbc:mysql://localhost:3306/snackbar", "root", "password");
        }catch (Exception erro){
            throw new RuntimeException("Erro de conexao com a bd: "+erro);
        }
    }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
}
